### ISSUE TITLE
Cannot use local IPFS node: TypeError: Failed to fetch

### ISSUE THREAD

**Issue by q9f** [dappnode/sdk-publish#10]
Setting IPFS API to `http://127.0.0.1:5001` results in:

```
TypeError: Failed to fetch
    at fetch (https://dappnode.github.io/sdk-publish/static/js/2.aadeb2d3.chunk.js:2:949159)
    at r.<anonymous> (https://dappnode.github.io/sdk-publish/static/js/2.aadeb2d3.chunk.js:2:651795)
    at c (https://dappnode.github.io/sdk-publish/static/js/2.aadeb2d3.chunk.js:2:835696)
    at Generator._invoke (https://dappnode.github.io/sdk-publish/static/js/2.aadeb2d3.chunk.js:2:835449)
    at Generator.next (https://dappnode.github.io/sdk-publish/static/js/2.aadeb2d3.chunk.js:2:836055)
    at r (https://dappnode.github.io/sdk-publish/static/js/2.aadeb2d3.chunk.js:2:310)
    at u (https://dappnode.github.io/sdk-publish/static/js/2.aadeb2d3.chunk.js:2:521)
    at https://dappnode.github.io/sdk-publish/static/js/2.aadeb2d3.chunk.js:2:580
    at new Promise (<anonymous>)
    at r.<anonymous> (https://dappnode.github.io/sdk-publish/static/js/2.aadeb2d3.chunk.js:2:461)
```

**Comment by dapplion** [comment]
Hi @q9f <3

- Can you open the networking tab of your browser and confirm the exact URL that causes the `Failed to fetch` error?
- I'm sure it's available but can you double check that `http://127.0.0.1:5001` is available from your browser? You can open the browser console and run
```js
fetch("http://127.0.0.1:5001/api/v0/version", {method: "POST"})
```

**Comment by jaybuidl** [comment]
I have the same issue, apparently related to mixed content because the website serves `https` but the IPFS API is `http`

```
fetch.browser.js:106 Mixed Content: The page at 'https://dappnode.github.io/sdk-publish/?r=xxxx&v=xxx&h=xxxxx' 
was loaded over HTTPS, but requested an insecure resource 'http://ipfs.dappnode:8080/api/v0/block/get?arg=xxxx'. 
This request has been blocked; the content must be served over HTTPS.
fetch @ fetch.browser.js:106
----
App.tsx:184 TypeError: Failed to fetch
    at fetch (fetch.browser.js:106:7)
    at r.<anonymous> (http.js:129:7)
    at c (runtime.js:63:40)
    at Generator._invoke (runtime.js:293:22)
    at Generator.next (runtime.js:118:21)
    at r (asyncToGenerator.js:3:20)
    at u (asyncToGenerator.js:25:9)
    at asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at r.<anonymous> (asyncToGenerator.js:21:12)
```
