### ISSUE TITLE
Invalid byte while expecting start of value: 0x12

### ISSUE THREAD

**Issue by q9f** [dappnode/sdk-publish#9]
1. Package: `sepolia-geth.public.dappnode.eth`
1. Developer address: `0xe611a720778a5f6723d6b4866F84828504657181`
1. Next version: `0.1.2`
1. Release hash: `/ipfs/QmWz6qUN8jTqxvnVKMwEjTXdwQaYLiwhMFikfZjBaABEWP`
2. Click "Sign release" and sing mesage in MetaMask
1. Result: `Invalid byte while expecting start of value: 0x12`

```
HTTPError: Invalid byte while expecting start of value: 0x12
    at https://dappnode.github.io/sdk-publish/static/js/2.aadeb2d3.chunk.js:2:557949
    at c (https://dappnode.github.io/sdk-publish/static/js/2.aadeb2d3.chunk.js:2:835696)
    at Generator._invoke (https://dappnode.github.io/sdk-publish/static/js/2.aadeb2d3.chunk.js:2:835449)
    at Generator.next (https://dappnode.github.io/sdk-publish/static/js/2.aadeb2d3.chunk.js:2:836055)
    at r (https://dappnode.github.io/sdk-publish/static/js/2.aadeb2d3.chunk.js:2:310)
    at u (https://dappnode.github.io/sdk-publish/static/js/2.aadeb2d3.chunk.js:2:521)
```

Using `https://ipfs.infura.io:5001` as IPFS API URL.

**Comment by MysticRyuujin** [comment]
I have the same issue.

1. Package: `dshackle.public.dappnode.eth`
2. Developer address: `0x8aE6422631292c31aeeB2efe154d6326f703F46b`
3. Next version: `0.2.0`
4. Release hash: `/ipfs/QmXP9rV4kSdLEFrNRGxRrXhTAjMDKTe45tFpa2udZG3uLA`

Everything else is exactly the same as reported above with MetaMask signing.

https://dappnode.github.io/sdk-publish/?r=dshackle.public.dappnode.eth&v=0.2.0&h=%2Fipfs%2FQmXP9rV4kSdLEFrNRGxRrXhTAjMDKTe45tFpa2udZG3uLA

**Comment by dapplion** [comment]
Thank you for your patience, I confirm that #12 fixes the issue, please try again now :pray:
